### PR TITLE
Update manifest.webapp

### PR DESCRIPTION
**Pull request by airon90**
- Added Italian (it) and Esperanto (eo) localizations
- Added default locale

### CODE REVIEW

**Comment by aroblu94** [comment]
Esperanto?

**Comment by Mte90** [comment]
@aroblu94 @nicokant94 ignore the pr now?

**Comment by Airon90** [comment]
@Mte90 Why do you think my PR should be rejected?

**Comment by Mte90** [comment]
@aroblu94 @nicokant94 ragazzi che vogliamo fare?

**Comment by aronnebrivio** [comment]
@Airon90 merge fatto, grazie!! :)

**Comment by airon90** [comment]
Grazie a te ;)

**Pull request merged**
